apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minikube-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  description: Minikube platform add-ons managed by gitops-platform-minikube.
  sourceRepos:
    - https://istio-release.storage.googleapis.com/charts
    - quay.io/jetstack/charts
    - https://github.com/mahesh-newdevops/gitops-platform-minikube.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: istio-system
    - server: https://kubernetes.default.svc
      namespace: istio-ingress
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
