apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minikube-workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Minikube GitOps workloads managed by gitops-platform-minikube.
  sourceRepos:
    - https://github.com/mahesh-newdevops/gitops-platform-minikube.git
    - https://github.com/mahesh-newdevops/microservices-deployment.git
    - https://github.com/mahesh-newdevops/monitoring-application.git
    - https://kubernetes-sigs.github.io/headlamp/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: microservices
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: headlamp
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
