grafana:
  enabled: true
  adminPassword: admin123
  service:
    type: NodePort
    nodePort: 32000
  defaultDashboardsTimezone: browser
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3200
      isDefault: false
      jsonData:
        tracesToLogsV2:
          datasourceUid: Loki
          spanStartTimeShift: -1h
          spanEndTimeShift: 1h
        serviceMap:
          datasourceUid: Prometheus

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    retention: 7d
    storageSpec: {}

alertmanager:
  enabled: true

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
